bundler_args: --deployment --without development
cache:
  bundler: true
  directories:
  - $(rvm gemdir)
  - build
  - node_modules
env:
  global:
  # CloudFront distribution ID
  - secure: "hbOnJbFFOUCkaR7kxgCX8Z2ExmJZNLSLlEv7sOlNCLoBTgH1EwULG4gjX+5rTLgELcbqIPEy+ZUBV6oZSF4k3we5W2xmb7a0x09WY4MbN38Ovv1VmYQIuDRZlFm8aKqXoUzJaOeUE+E5BDs1J4X03xOZcyQq4nrCk5xKuFriqVg="
  # AWS access key ID
  - secure: "BoEZqOpxDMmu3AcW3OZMxBzM6K4DOkdx1ig7VXIjRB6ffrKoXMdGpDMDyTc9IGy7bUfpWeQcuHjToDsd7K9mE6vF5v5HMkBlsUIUlE+V+cMzZt5w917+Rb6Md+Qq0VLr+ibNR59eDhA4774beMqeERPVTZEgHAFhkLMOlKWLrL4="
  # AWS secret access key
  - secure: "L3Owj6zOxnGNwdoyWcNGOxkSXDf27U7A7t3Qwe5NwppcuWY2bpzzffMkLIhM/HOhRT9tBiBdEYmkWwZTjIGp6O1+AOfVFxCfjQbjfkam3mdcDsR0UouIkh4R+5PFl2XwG9Gdeuib0QPVwf8jJ6eHyG26TyBceLHqoAAfl5OoWBo="
  - AWS_S3_BUCKET=style.chef.io
  - AWS_DEFAULT_REGION=us-west-1
  - SPEC_OPTS="--format doc"
before_script:
- npm install
script:
- bundle exec rake test
- bundle exec rake publish
sudo: false
deploy:
  - provider: releases
    api_key:
      secure: "ZLJrqlUdxePqDGFY3VFh3vVD7y4hqePT1QmbWLFHMIlcqsvqK7ntqhMFunm5l42YDN6ufuzOqJGSTGbdPmEFo7v/Ij5hmHrAy/ja/jUjSfBillp0QzTBfi19+c+cnKwOqdLMdSSynow06tvQvCoT1RLl2AOgTCwHZNOCZ+OgwtE="
    file_glob: true
    file:
    - chef-web-core-*.tgz
    skip_cleanup: true
    on:
      tags: true
      repo: chef/chef-web-core
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET
    local-dir: dist
    upload-dir: dist/$TRAVIS_TAG
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: chef/chef-web-core
